version: '3.7'
services:
  web:
    image: nginx:1.23.3
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    restart: always
    ports:
      - "5000:80"
    environment:
      - NGINX_PORT=80
